# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
